export const SOCIETY_TAGS = [
  "Schwarmintelligenz",
  "KI-Kontrolle",
  "Eugenik-Kult",
  "Demokratie",
  "Primitiv",
  "Gildenrat",
  "Adelsherrschaft",
  "Verlassen",
  "Tyrannei",
  "Polizeistaat",
  "Mega-Konzern",
  "Oligarchie",
  "Theokratie",
  "Militärjunta",
  "Technokratie",
  "Anarchie",
] as const;

export const WORLD_TYPES = [
  "Kristallwelt",
  "Raumstation",
  "Sumpf",
  "Felsig",
  "Arktisch",
  "Erdähnlich",
  "Ozean",
  "Wüste",
  "Dschungel",
  "Asteroid",
  "Vulkanisch",
] as const;

export const GENERAL_TAGS = [
  "Fremdartige Ruinen",
  "Geheim",
  "Ehemaliges Schlachtfeld",
  "Uraltes Archiv",
  "Uralter Schrecken",
  "Frisch kolonisiert",
  "Isoliert / Vergessen",
  "Agrarkolonie",
  "Industrieplanet",
  "Minenplanet",
  "Schrottplatz / Oberfläche voller Wracks",
  "Pilgerstätte",
  "Regionalmacht",
  "Aufsteigende Regionalmacht",
  "Ehemalige Regionalmacht",
  "Psionischer Kult",
  "Psionische Akademie",
  "Akademie",
  "Forschungsstation",
  "Raumschiffwerft",
  "Handelsposten",
  "Piratenbasis",
  "Cyborgs",
  "Dem Untergang geweiht (Ökologie, Krieg, Seuche. etc)",
  "Gefährlicher Virus",
  "Zombies",
  "Sklaverei",
  "Kalter Krieg",
  "Bürgerkrieg",
  "Heiliger Krieg",
  "Kanibalen",
  "Fremdenfeindlich",
  "Toxische Biosphäre",
  "Radioaktive Biosphäre",
  "Patriarchat",
  "Matriarchat",
  "Vergnügungskult (Exzesse & Lust)",
  "Gefängnisplanet",
  "Militärstützpunkt",
  "Schmugglernest",
  "Flüchtlinge",
  "Vergessene Superwaffe",
  "Sperrgebiet",
  "Psionische Anomalie",
  "Gefährliche Tiere",
  "Orbitales Trümmerfeld",
  "Planetarer Schild",
  "Megafabrik",
  "Dinosaurier",
  "Monster",
] as const;
