export const WORLD_TYPES = [
  "Kristallwelt",
  "Raumstation",
  "Sumpf",
  "Felsig",
  "Arktisch",
  "Erdähnlich",
  "Ozean",
  "Wüste",
  "Dschungel",
  "Asteroid",
  "Vulkanisch",
] as const;

export const SOCIETY_TAGS = [
  "Schwarmintelligenz",
  "KI-Kontrolle",
  "Eugenik-Kult",
  "Demokratie",
  "Primitiv",
  "Gildenrat",
  "Adelsherrschaft",
  "Verlassen",
  "Tyrannei",
  "Polizeistaat",
  "Mega-Konzern",
  "Oligarchie",
  "Theokratie",
  "Militärjunta",
  "Technokratie",
  "Anarchie",
] as const;

export const GENERAL_TAGS = [
  "Fremdartige Ruinen",
  "Geheim",
  "Ehemaliges Schlachtfeld",
  "Uraltes Archiv",
  "Uralter Schrecken",
  "Frisch kolonisiert",
  "Isoliert / Vergessen",
  "Agrarkolonie",
  "Industrieplanet",
  "Minenplanet",
  "Schrottwelt",
  "Pilgerstätte",
  "Regionalmacht",
  "Aufsteigende Regionalmacht",
  "Ehemalige Regionalmacht",
  "Psionischer Kult",
  "Psionische Akademie",
  "Akademie",
  "Forschungsstation",
  "Raumschiffwerft",
  "Handelsposten",
  "Piratenbasis",
  "Roboter Rebellion",
  "Dem Untergang geweiht",
  "Gefährlicher Virus",
  "Zombies",
  "Sklaverei",
  "Kalter Krieg",
  "Bürgerkrieg",
  "Heiliger Krieg",
  "Kanibalen",
  "Fremdenfeindlich",
  "Toxische Biosphäre",
  "Radioaktive Biosphäre",
  "Patriarchat",
  "Matriarchat",
  "Vergnügungskult",
  "Gefängnisplanet",
  "Militärstützpunkt",
  "Schmugglernest",
  "Flüchtlinge",
  "Vergessene Superwaffe",
  "Sperrgebiet",
  "Psionische Anomalie",
  "Gefährliche Tiere",
  "Orbitales Trümmerfeld",
  "Planetarer Schild",
  "Stadtplanet",
  "Dinosaurier",
  "Monster",
] as const;

export const FIELD_TITLES = [
  "Altair",
  "Antares",
  "Arcturus",
  "Betelgeuse",
  "Canopus",
  "Capella",
  "Deneb",
  "Ixil",
  "Polaris",
  "Procyon",
  "Rigel",
  "Sirius",
  "Spica",
  "Vega",
  "Zubenel",
  "Acrux",
  "Bellatrix",
  "Dubhe",
  "Eltanin",
  "Gacrux",
  "Hadar",
  "Izar",
  "Kochab",
  "Mimosa",
  "Naos",
  "Pollux",
  "Rasalhague",
  "Saiph",
  "Thuban",
  "Unukalhai",
  "Vindemiatrix",
  "Wezen",
  "Zosma",
  "Aldebaran",
  "Alhena",
  "Alnair",
  "Ankaa",
  "Caph",
  "Diphda",
  "Enif",
  "Gienah",
  "Hamal",
  "Izar",
  "Kaus",
  "Lesath",
  "Merak",
  "Nashira",
  "Okul",
  "Phact",
  "Rastaban",
  "Sabik",
  "Talitha",
  "Yildun",
  "Achernar",
  "Alcyone",
  "Alnitak",
  "Alphard",
  "Alshain",
  "Atria",
  "Cursa",
  "Electra",
  "Hyadum",
  "Maia",
  "Merope",
  "Mintaka",
  "Pleione",
  "Sadalmelik",
  "Scheat",
  "Shedir",
  "Sterope",
  "Taygeta",
  "Thalassa",
  "Adhara",
  "Alya",
  "Asellus",
  "Celaeno",
  "Chara",
  "Corvus",
  "Dhalim",
  "Errai",
  "Foramen",
  "Graffis",
  "Helion",
  "Ilyra",
  "Jadara",
  "Kaleth",
  "Lunara",
  "Myrris",
  "Nerath",
  "Orivis",
  "Pheron",
  "Quyara",
  "Raveth",
  "Selora",
  "Thyros",
  "Ulanis",
  "Verath",
  "Xandor",
  "Yelora",
  "Zeraphis",
] as const;
