import { create } from "zustand";
import { SectorStore } from "./types";
import { generateSector } from "./sectorHelper";

export const useSectorStore = create<SectorStore>((set) => ({
  selectedInfoMenu: null,
  oldSelectedInfoMenu: null,

  openSectorInfo: () =>
    set({
      selectedFieldIndex: null,
      selectedWorldIndex: null,
      selectedInfoMenu: "SectorInfo",
    }),

  worldTypeTags: [
    "Kristallwelt",
    "Raumstation",
    "Sumpf",
    "Felsig",
    "Arktisch",
    "Erdähnlich",
    "Ozean",
    "Wüste",
    "Dschungel",
    "Asteroid",
    "Vulkanisch",
  ],
  worldSocietyTags: [
    "Schwarmintelligenz",
    "KI-Kontrolle",
    "Eugenik-Kult",
    "Demokratie",
    "Primitiv",
    "Gildenrat",
    "Adelsherrschaft",
    "Verlassen",
    "Tyrannei",
    "Polizeistaat",
    "Mega-Konzern",
    "Oligarchie",
    "Theokratie",
    "Militärjunta",
    "Technokratie",
    "Anarchie",
  ],
  worldGeneralTags: [
    "Akademie",
    "Agrarkolonie",
    "Altes Schlachtfeld",
    "Aufsteigende Regionalmacht",
    "Bürgerkrieg",
    "Dem Untergang geweiht",
    "Dinosaurier",
    "Diplomatisches Zentrum",
    "Ehemalige Regionalmacht",
    "Flüchtlinge",
    "Forschungsstation",
    "Fremdartige Ruinen",
    "Fremdenfeindlich",
    "Frisch kolonisiert",
    "Gefährliche Tiere",
    "Gefährlicher Virus",
    "Gefängniswelt",
    "Geheim",
    "Handelsposten",
    "Heiliger Krieg",
    "Industriewelt",
    "Isoliert / Vergessen",
    "Kanibalen",
    "Kalter Krieg",
    "Matriarchat",
    "Metropolwelt",
    "Militärstützpunkt",
    "Minenplanet",
    "Monster",
    "Orbitales Trümmerfeld",
    "Patriarchat",
    "Pilgerstätte",
    "Piratenbasis",
    "Psionische Akademie",
    "Psionische Anomalie",
    "Psionischer Kult",
    "Radioaktive Biosphäre",
    "Regionalmacht",
    "Roboter Rebellion",
    "Raumschiffwerft",
    "Schrottwelt",
    "Schmugglernest",
    "Sklaverei",
    "Sperrgebiet",
    "Toxische Biosphäre",
    "Uralter Schrecken",
    "Uraltes Archiv",
    "Vergessene Superwaffe",
    "Vergnügungskult",
    "Zombies",
  ],
  sectorGeneralTags: [
    "Alte Prophezeiung",
    "Altes Machtzentrum",
    "Altes Schlachtfeld",
    "Anarchie",
    "Bürgerkrieg",
    "Diplomatisches Zentrum",
    "Drogenkartelle",
    "Flottensützpunkt",
    "Flüchtlinge",
    "Fraktionskrieg",
    "Fremdartige Aliens",
    "Gefährliche Artefakte",
    "Geisterschiffe",
    "Handelskrieg",
    "Handelskrieg",
    "Handelszentrum",
    "Heiliger Krieg",
    "Hungersnot",
    "Industriezentrum",
    "Invasion",
    "Katastrophe",
    "KI-Overloard",
    "Konzernkrieg",
    "Kreuzzug",
    "Kulturelles Zentrum",
    "Legendäre Werft",
    "Liga der Planeten",
    "Mächtiger Warlord",
    "Mutanten",
    "Nanoschwarm",
    "Nomadenflotte",
    "Pandemie",
    "Pilgerroute",
    "Piratennest",
    "Psionische Anomalien",
    "Psionischer Kult",
    "Rebellion",
    "Religiös",
    "Roboter Rebellion",
    "Schattenkrieg",
    "Schmugglerhafen",
    "Schwarm-Infektion",
    "Sektor Krieg",
    "Sklavenhandel",
    "Tyranisches Imperium",
    "Unzivilisiert",
    "Warp Anomalie",
    "Weltraumwahle",
    "Wichtige Warproute",
    "Zerbrochene Allianz",
  ],
  stellarNames: [
    "Altair",
    "Antares",
    "Arcturus",
    "Betelgeuse",
    "Canopus",
    "Capella",
    "Deneb",
    "Ixil",
    "Polaris",
    "Procyon",
    "Rigel",
    "Sirius",
    "Spica",
    "Vega",
    "Zubenel",
    "Acrux",
    "Bellatrix",
    "Dubhe",
    "Eltanin",
    "Gacrux",
    "Hadar",
    "Izar",
    "Kochab",
    "Mimosa",
    "Naos",
    "Pollux",
    "Rasalhague",
    "Saiph",
    "Thuban",
    "Unukalhai",
    "Vindemiatrix",
    "Wezen",
    "Zosma",
    "Aldebaran",
    "Alhena",
    "Alnair",
    "Ankaa",
    "Caph",
    "Diphda",
    "Enif",
    "Gienah",
    "Hamal",
    "Izar",
    "Kaus",
    "Lesath",
    "Merak",
    "Nashira",
    "Okul",
    "Phact",
    "Rastaban",
    "Sabik",
    "Talitha",
    "Yildun",
    "Achernar",
    "Alcyone",
    "Alnitak",
    "Alphard",
    "Alshain",
    "Atria",
    "Cursa",
    "Electra",
    "Hyadum",
    "Maia",
    "Merope",
    "Mintaka",
    "Pleione",
    "Sadalmelik",
    "Scheat",
    "Shedir",
    "Sterope",
    "Taygeta",
    "Thalassa",
    "Adhara",
    "Alya",
    "Asellus",
    "Celaeno",
    "Chara",
    "Corvus",
    "Dhalim",
    "Errai",
    "Foramen",
    "Graffis",
    "Helion",
    "Ilyra",
    "Jadara",
    "Kaleth",
    "Lunara",
    "Myrris",
    "Nerath",
    "Orivis",
    "Pheron",
    "Quyara",
    "Raveth",
    "Selora",
    "Thyros",
    "Ulanis",
    "Verath",
    "Xandor",
    "Yelora",
    "Zeraphis",
  ],

  sector: null,
  setSector: (sector) => set({ sector }),
  newSector: () =>
    set({
      selectedInfoMenu: null,
      oldSelectedInfoMenu: null,
      selectedFieldIndex: null,
      selectedWorldIndex: null,
      sector: generateSector(),
    }),

  selectedFieldIndex: null,
  setSelectedFieldIndex: (index) =>
    set({
      selectedInfoMenu: "FieldInfo",
      selectedFieldIndex: index,
    }),

  selectedWorldIndex: null,
  setSelectedWorldIndex: (indices) =>
    set({
      selectedInfoMenu: "WorldInfo",
      selectedWorldIndex: indices,
    }),

  toggleSaveMenu: () =>
    set((state) =>
      state.selectedInfoMenu === "SaveMenu"
        ? {
            selectedInfoMenu: state.oldSelectedInfoMenu ?? null,
            oldSelectedInfoMenu: null,
          }
        : {
            oldSelectedInfoMenu: state.selectedInfoMenu,
            selectedInfoMenu: "SaveMenu",
          }
    ),
}));
