export const worldTypeTags = [
  "Kristallwelt",
  "Raumstation",
  "Sumpf",
  "Felsig",
  "Arktisch",
  "Erdähnlich",
  "Ozean",
  "Wüste",
  "Dschungel",
  "Asteroid",
  "Vulkanisch",
];

export const worldSocietyTags = [
  "Schwarmintelligenz",
  "KI-Kontrolle",
  "Eugenik-Kult",
  "Demokratie",
  "Primitiv",
  "Gildenrat",
  "Adelsherrschaft",
  "Verlassen",
  "Tyrannei",
  "Polizeistaat",
  "Mega-Konzern",
  "Oligarchie",
  "Theokratie",
  "Militärjunta",
  "Technokratie",
  "Anarchie",
];

export const worldGeneralTags = [
  "Akademie",
  "Agrarkolonie",
  "Altes Schlachtfeld",
  "Aufsteigende Regionalmacht",
  "Bürgerkrieg",
  "Dem Untergang geweiht",
  "Dinosaurier",
  "Diplomatisches Zentrum",
  "Ehemalige Regionalmacht",
  "Flüchtlinge",
  "Forschungsstation",
  "Fremdartige Ruinen",
  "Fremdenfeindlich",
  "Frisch kolonisiert",
  "Gefährliche Tiere",
  "Gefährlicher Virus",
  "Gefängniswelt",
  "Geheim",
  "Handelsposten",
  "Heiliger Krieg",
  "Industriewelt",
  "Isoliert / Vergessen",
  "Kanibalen",
  "Kalter Krieg",
  "Matriarchat",
  "Metropolwelt",
  "Militärstützpunkt",
  "Minenplanet",
  "Monster",
  "Orbitales Trümmerfeld",
  "Patriarchat",
  "Pilgerstätte",
  "Piratenbasis",
  "Psionische Akademie",
  "Psionische Anomalie",
  "Psionischer Kult",
  "Radioaktive Biosphäre",
  "Regionalmacht",
  "Roboter Rebellion",
  "Raumschiffwerft",
  "Schrottwelt",
  "Schmugglernest",
  "Sklaverei",
  "Sperrgebiet",
  "Toxische Biosphäre",
  "Uralter Schrecken",
  "Uraltes Archiv",
  "Vergessene Superwaffe",
  "Vergnügungskult",
  "Zombies",
];

export const sectorTags = [
  "Alte Prophezeiung",
  "Altes Schlachtfeld",
  "Anarchie",
  "Bürgerkrieg",
  "Dem Untergang geweiht",
  "Diplomatisches Zentrum",
  "Drogenkartelle",
  "Flottensützpunkt",
  "Flüchtlinge",
  "Fraktionskrieg",
  "Fremdartige Aliens",
  "Gefährliche Artefakte",
  "Geheimbund",
  "Geisterschiffe",
  "Grenzland",
  "Handelskrieg",
  "Handelszentrum",
  "Heiliger Krieg",
  "Hungersnot",
  "Industriezentrum",
  "Invasion",
  "Isoliert",
  "Kalter Krieg",
  "KI-Overloard",
  "Konzernkrieg",
  "Kulturelles Zentrum",
  "Liga der Planeten",
  "Mächtiger Warlord",
  "Maschinenkulte",
  "Mutanten",
  "Nanoschwarm",
  "Nomadenflotte",
  "Pandemie",
  "Pilgerroute",
  "Piratennest",
  "Psionische Anomalien",
  "Psionischer Kult",
  "Rebellion",
  "Religiös",
  "Roboter Rebellion",
  "Schattenkrieg",
  "Schmugglerhafen",
  "Schwarm-Infektion",
  "Sektor Krieg",
  "Sklavenhandel",
  "Tyranisches Imperium",
  "Verfallendes Machtzentrum",
  "Warp Anomalie",
  "Weltraumwahle",
  "Wichtige Warproute",
];

export const stellarNames = [
  "Altair",
  "Antares",
  "Arcturus",
  "Betelgeuse",
  "Canopus",
  "Capella",
  "Deneb",
  "Ixil",
  "Polaris",
  "Procyon",
  "Rigel",
  "Sirius",
  "Spica",
  "Vega",
  "Zubenel",
  "Acrux",
  "Bellatrix",
  "Dubhe",
  "Eltanin",
  "Gacrux",
  "Hadar",
  "Izar",
  "Kochab",
  "Mimosa",
  "Naos",
  "Pollux",
  "Rasalhague",
  "Saiph",
  "Thuban",
  "Unukalhai",
  "Vindemiatrix",
  "Wezen",
  "Zosma",
  "Aldebaran",
  "Alhena",
  "Alnair",
  "Ankaa",
  "Caph",
  "Diphda",
  "Enif",
  "Gienah",
  "Hamal",
  "Izar",
  "Kaus",
  "Lesath",
  "Merak",
  "Nashira",
  "Okul",
  "Phact",
  "Rastaban",
  "Sabik",
  "Talitha",
  "Yildun",
  "Achernar",
  "Alcyone",
  "Alnitak",
  "Alphard",
  "Alshain",
  "Atria",
  "Cursa",
  "Electra",
  "Hyadum",
  "Maia",
  "Merope",
  "Mintaka",
  "Pleione",
  "Sadalmelik",
  "Scheat",
  "Shedir",
  "Sterope",
  "Taygeta",
  "Thalassa",
  "Adhara",
  "Alya",
  "Asellus",
  "Celaeno",
  "Chara",
  "Corvus",
  "Dhalim",
  "Errai",
  "Foramen",
  "Graffis",
  "Helion",
  "Ilyra",
  "Jadara",
  "Kaleth",
  "Lunara",
  "Myrris",
  "Nerath",
  "Orivis",
  "Pheron",
  "Quyara",
  "Raveth",
  "Selora",
  "Thyros",
  "Ulanis",
  "Verath",
  "Xandor",
  "Yelora",
  "Zeraphis",
];
